from enum import Enum


class OBDConstants(Enum):
    WIDGET_WIDTH_HINT = 400
    WIDGET_HEIGHT_HINT = 400
    WIDGET_SCALE_FACTOR_DIV = 200
    WIDGET_INNER_LEFT = -100
    WIDGET_INNER_TOP = -100
    WIDGET_INNER_WIDTH = 200
    WIDGET_INNER_HEIGHT = 200
    WIDGET_NAME_POS = 90
